### ISSUE TITLE
Py4JJavaError on Jupyter Notebook

### ISSUE THREAD

**Issue by emrekutlug** [IBM/prediction-using-watson-machine-learning#11]
I am getting following error while trying to run following code:

"DRUG_TRAIN_DATA_UPDATED_data = spark.read.jdbc(db2_credentials['jdbcurl'], table=tablename, properties=db2_credentials)"

the error is:

Py4JJavaError: An error occurred while calling o127.jdbc. : com.ibm.db2.jcc.am.SqlSyntaxErrorException: DB2 SQL Error: SQLCODE=-204, SQLSTATE=42704, SQLERRMC=DASH105563.DRUG_TRAIN_DATA_UPDATED, DRIVER=4.23.42

I properly add db2_service_credentials.

thanks in advance.

**Comment by scottdangelo** [comment]
I am able to run the notebook successfully.
I believe you have an issue with your db2 credentials. If I use some old and invalid credentials, I am able to reproduce your error.
Can you please re-check that you have the correct credentials? Perhaps re-create the DB2 instance, and re-create the database?

**Comment by emrekutlug** [comment]
I check that my credentials are correct by re-creating the DB2 instance and re-creating the database. However, I am still getting the same error.

**Comment by stevemar** [comment]
We're archiving this repo, please see https://github.com/IBM/monitor-wml-model-with-watson-openscale as an alternative
